language: generic

sudo: false

env:
  global:
    - secure: "GBUWN7mc4pdUrR15grztD6NchiYhFT70ap6hKWIf0d3XwfWSQo0I85qnIqSWrzuThMp7qjJMCvemrPpXBZngUL3LvYi1t9LoF5shokO5tD3qLnaT0mFtW5r2JuOFR+7dMmbTklVqmB3zX+/JPn+L3qeyDn7mwbW++lcoe2jA6qY="

before_install:
  - wget http://bit.ly/miniconda -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update conda --yes
  - conda config --add channels conda-forge --force

install:
  - conda create --yes -n TEST python=3.5 --file requirements.txt
  - source activate TEST

script:
  - set -e
  - mkdocs build --clean --verbose
  - doctr deploy --built-docs=_site .
